services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/devops  
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050 
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  
networks:
  mern_network:
    driver: bridge 
volumes:
  mongo-data:
    driver: local